services:
  web:
    build: .
    # ports:
    #   - "3000:3000"
    #   - "8000:8000"
    depends_on:
      - caddy

  caddy:
    image: caddy:2.9.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "9000:9000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
