version: "3"

includes:
  web:
    taskfile: ~/github/webserver-personal/Taskfile.yml
    dir: ~/github/webserver-personal
    optional: true
    internal: true

tasks:
  install:
    desc: Install project dependencies and setup pre-commit
    cmds:
      - uv sync --dev
      - task pre-commit-install
  lock:
    desc: Lock and updated dependencies
    cmds:
      - uv lock -U

  pre-commit-install:
    desc: One off setup of pre-commit (uses venv to install pre-commit)
    cmds:
      - uv run --dev pre-commit install

  pre-commit-all:
    desc: Run pre-commit on all files.
    cmds:
      - uv run --dev pre-commit run --all-files --verbose

  run:
    desc: Run reflex locally
    cmds:
      - uv run reflex migrate && uv run reflex run

  run-compose:
    desc: Run backend similar to production
    cmds:
      - docker compose down
      - docker compose up --watch --force-recreate
