version: "3"

vars:
  TEST_DROPLET: "test-droplet"
  DO_SSH_KEY: "tim-linux"

tasks:
  poetry_install:
    desc: Run poetry install
    cmds:
      - poetry check
      - poetry install --sync

  poetry_update:
    desc: Run poetry update
    cmds:
      - poetry lock --regenerate
      - task poetry_install

  check-no-staged-changes:
    desc: Check if there are any staged changes
    # Useful when a task will add and commit specific files (don't want to commit other staged changes)
    silent: true
    cmds:
      - git diff --quiet --staged || (echo "There are staged changes. Please unstage or commit them first." && exit 1)

  poetry_export:
    desc: Export poetry.lock to requirements.txt
    sources:
      - pyproject.toml
      - poetry.lock
    generates:
      - requirements.txt
    deps:
      - check-no-staged-changes
    cmds:
      - poetry check && poetry export -f requirements.txt --output requirements.txt --without-hashes
      - git add requirements.txt
      - git commit -q -m "update backend requirements.txt" &> /dev/null && echo "Updated requirements.txt" || echo "No changes to requirements.txt"

  run-docker:
    desc: Run via docker (after exporing etc.)
    cmds:
      - task: poetry_export
      - docker build -t reflex-test:test-build . && docker run -p 3000:3000 -p 8000:8000 reflex-test:test-build

  droplet-create:
    desc: Create a new droplet
    vars:
      SSH_KEY_ID:
        sh: doctl compute ssh-key list | grep {{.DO_SSH_KEY}} | awk '{print $1}'
    cmds:
      - scripts/create-droplet.sh {{.TEST_DROPLET}} {{.SSH_KEY_ID}}
      - ssh {{.TEST_DROPLET}} "bash -s" < ~/dotfiles/scripts/setup_docker.sh
      - ssh {{.TEST_DROPLET}} "git clone https://github.com/TimChild/reflex_test.git"

  temp:
    desc: Temporary task
    cmds:
      # Get the IP of the newly created droplet
      - echo $(doctl compute droplet get {{.TEST_DROPLET}} --format PublicIPv4 --no-header)

  deploy:
    desc: Deploy to droplet
    cmds:
      - task: poetry_export
      - git push
      - ssh {{.TEST_DROPLET}} "bash -s" < scripts/remote-deploy-script.sh
